version: "3.8"

services:
  db:
    image: mysql:8
    restart: always
    network_mode: "host"
    volumes:
      - "/var/lib/mysql-docker/db:/var/lib/mysql"
      - "/usr/share/zoneinfo/America/New_York:/etc/localtime:ro"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: "dbhost"
      MYSQL_USER: "dbhost"
      MYSQL_TCP_PORT: "3306"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
