version: "3.8"

services:
  db:
    image: mysql:8
    container_name: mysql-dbhost
    restart: always
    networks:
      - wings0
    ports:
      - "$MYSQL_IP:$MYSQL_PORT:$MYSQL_IP:$MYSQL_PORT"
    volumes:
      - "/var/lib/mysql-dbhost/db:/var/lib/mysql"
      - "/usr/share/zoneinfo/America/New_York:/etc/localtime:ro"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: "dbhost"
      MYSQL_USER: "dbhost"
      MYSQL_TCP_PORT: "$MYSQL_PORT"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  wings0:
    external: true
